name: Keep Supabase Awake

on:
  schedule:
    - cron: "0 8 * * 1" # Tous les lundis à 08h UTC
  workflow_dispatch: # Permet de le lancer manuellement aussi

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Make GET request to Supabase
        run: |
          curl -I https://cathecopte.vercel.app/
